import base64
from abc import ABC, abstractmethod

import requests

from config.ai_config import AI_CONFIG
from services.ai_settings_service import AISettingsService
from services.logging_service import LoggingService


logger = LoggingService.get_logger("ai")


class VisionProvider(ABC):

    def __init__(self, settings=None):

        self.settings = settings or {}

    @abstractmethod
    def analyze(self, image_path: str) -> str:
        pass

    def model_name(self):

        return self.settings.get("model", "unknown")


class OllamaVisionProvider(VisionProvider):

    def analyze(self, image_path: str) -> str:

        with open(image_path, "rb") as image:
            encoded = base64.b64encode(image.read()).decode("utf-8")

        model = self.model_name()

        prompt = """
Describe only what is visibly present in this image.

Return JSON only. No markdown. No prose before or after JSON.
Do not invent identities, ranks, locations, department names, incident types,
or apparatus types unless visible evidence supports them. Use "unknown" when
unclear. Use empty lists instead of guesses.

Schema:
{
  "description": "Clear factual description of visible content.",
  "people_count": 0,
  "people": [],
  "apparatus": [],
  "equipment": [],
  "activities": [],
  "setting": "",
  "indoor_outdoor": "unknown",
  "training": false,
  "incident_scene": false,
  "public_education": false,
  "community_event": false,
  "safety_concerns": [],
  "public_use_risks": [],
  "confidence": 0.0,
  "model": "%s"
}
""" % model

        response = requests.post(
            self.settings.get("url"),
            json={
                "model": model,
                "prompt": prompt,
                "images": [encoded],
                "stream": False,
            },
            timeout=self.settings.get("timeout", 300),
        )
        response.raise_for_status()

        logger.info(
            "Ollama vision analysis completed model=%s",
            model
        )

        return response.json()["response"]


class MockVisionProvider(VisionProvider):

    def analyze(self, image_path: str) -> str:
        model = self.model_name()

        return """
{
  "description":"MOCK TEST ANALYSIS - test data only. This result was generated by the mock provider and does not inspect the selected image. Sample scene: firefighters in turnout gear using a hose line beside Engine 1 during an evening drill.",
  "scene_type":"training",
  "activity":"hose line training",
  "people_count":4,
  "apparatus":["Engine 1"],
  "equipment":["Hose line","SCBA","Nozzle"],
  "keywords":["mock provider","test data only","training","firefighter","ppe","safety","night drill"],
  "community_score":72,
  "recruitment_score":84,
  "education_score":78,
  "technical_score":81,
  "overall_score":82,
  "facebook_caption":"MOCK TEST CAPTION - Training night keeps our crews sharp and ready to serve.",
  "instagram_caption":"MOCK TEST CAPTION - Evening hose-line training with the crew.",
  "model":"%s"
}
""" % model


class VisionProviderRegistry:

    def __init__(self):

        self._providers = {}

    def register(self, name, provider_class):

        self._providers[name] = provider_class

    def create(self, name, settings=None):

        provider_class = self._providers.get(name)

        if provider_class is None:
            raise ValueError(f"Unknown vision provider: {name}")

        return provider_class(settings or {})

    def names(self):

        return sorted(self._providers.keys())


class VisionService:

    def __init__(
        self,
        provider: VisionProvider | None = None,
        config=None,
        registry=None,
        settings_service=None
    ):

        self.settings_service = settings_service or AISettingsService(
            base_config=config or AI_CONFIG
        )
        self.config = self.settings_service.effective_config()
        self.registry = registry or self._default_registry()
        self._provider_key = self.config.get(
            "default_provider",
            "ollama"
        )
        self._provider = provider or self._provider_from_config()

    def set_provider(self, provider: VisionProvider):

        self._provider = provider

    def switch_provider(self, provider_key, model=None):

        self.config = self.settings_service.save(
            provider=provider_key,
            vision_model=model
        )
        self._provider_key = self.config.get(
            "default_provider",
            provider_key
        )
        self._provider = self._provider_from_config()

        logger.info(
            "Vision provider switched provider=%s model=%s",
            self._provider_key,
            self.model_name()
        )

        return {
            "provider": self._provider_key,
            "model": self.model_name()
        }

    def analyze(self, image_path: str) -> str:

        return self._provider.analyze(image_path)

    def provider_name(self):

        return self._provider.__class__.__name__

    def provider_key(self):

        return self._provider_key

    def model_name(self):

        return self._provider.model_name()

    def available_providers(self):

        return self.registry.names()

    def provider_settings(self):

        return self.config.get("providers", {}).get(
            self._provider_key,
            {}
        )

    def _provider_from_config(self):

        provider_name = self.config.get("default_provider", "ollama")
        self._provider_key = provider_name
        provider_settings = self.config.get("providers", {}).get(
            provider_name,
            {}
        )

        return self.registry.create(
            provider_name,
            provider_settings
        )

    def _default_registry(self):

        registry = VisionProviderRegistry()

        registry.register(
            "ollama",
            OllamaVisionProvider
        )

        registry.register(
            "mock",
            MockVisionProvider
        )

        return registry
